### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by tve** [tve/flexdash#2]
### Big picture stuff
- [ ] improve connectivity using socketio into node-red using either uibuilder or https://github.com/wiktorschmidt/node-red-contrib-socketio
- [ ] support dynamic loading of Vue SFC components using https://github.com/FranckFreiburger/vue3-sfc-loader
- [ ] consider supporting mqtt over websocket
- [ ] figure out how to get historical data from server at load time
- [ ] implement a uPlot chart that uses database-backed data and supports pan&zoom
- [ ] implement a custom widget that uses multiple simple components

### UI stuff
- [ ] implement dragging and resizing of components in grid
- [ ] implement tree selector for dynamic binding of widget inputs
- [ ] implement real support for object and array inputs to widgets

### Machinery
- [ ] use dynamically loaded material-design-icons to save 1MB download
- [ ] see whether it's possible to tree-shake vuetify
- [ ] consider refactoring connections to allow multiple connections of the same type, e.g. multiple websockets, etc

### Further out
- [ ] migrate to Vue3 when Vuetify supports it

**Comment by gknops** [comment]
Re color picker: is there also a color picker widget? I'd like to be able to visualize and edit RGB values on my dashboard.
